language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: true
after_success:
  - julia -e 'import Pkg; Pkg.pkg"add Documenter")'
  - julia -e 'import JuliaForDataScience; include(joinpath(pathof(JuliaForDataScience), "..", "docs", "make.jl"))'
  # - julia -e 'import Pkg; cd(Pkg.dir("JuliaForDataScience")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
